name: ultra_level_pro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_reactive_ble: ^5.2.0
  go_router: ^12.1.0
  flutter_riverpod: ^2.4.5
  intl: ^0.18.1
  android_intent_plus: ^4.0.3
  otp: ^3.1.4
  simple_circular_progress_bar: ^1.0.2
  riverpod_annotation: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  permission_handler: ^11.0.1
  collection: ^1.17.2
  fluttertoast: ^8.2.5
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter:

  uses-material-design: true

  assets:
    - asserts/image/google.png
    - asserts/image/error.png
    - asserts/image/SMART_STARTER.png
    - asserts/image/ULTRALEVEL_DISPLAY.png
    - asserts/image/ULTRALEVEL_PRO.png
    - asserts/image/ULTRALEVEL_MAX.png
    - asserts/shape/horizontal_capsule.png
    - asserts/shape/horizontal_cylinder.png
    - asserts/shape/oval_tank.png
    - asserts/shape/horizontal_cylinder.png
    - asserts/shape/vertical_capsule.png
    - asserts/shape/rectangle_tank.png
    - asserts/shape/vertical_cylinder.png
    - asserts/shape/vertical_cylinder.png
    - asserts/shape/vertical_oval.png
    - asserts/shape/lookup.png
