// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl4DWOk3lpthD7M8pgryykl_avzRJV3u8',
    appId: '1:951810322846:web:305a6a6514bc546192e68f',
    messagingSenderId: '951810322846',
    projectId: 'ultralevel-pro',
    authDomain: 'ultralevel-pro.firebaseapp.com',
    storageBucket: 'ultralevel-pro.appspot.com',
    measurementId: 'G-KS5EPYYPKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhTtwm8RfxeyEM8Fz8J1kTn0XYTN1MnlA',
    appId: '1:951810322846:android:a5ae3a9f8314179792e68f',
    messagingSenderId: '951810322846',
    projectId: 'ultralevel-pro',
    storageBucket: 'ultralevel-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc4Dw9cmenZCDBiRJTlt0XYK_JrqmfVOQ',
    appId: '1:951810322846:ios:eddd88c1d8746b6492e68f',
    messagingSenderId: '951810322846',
    projectId: 'ultralevel-pro',
    storageBucket: 'ultralevel-pro.appspot.com',
    iosClientId: '951810322846-ms5llo5carv7aeq4khjjlpafpg3ndl69.apps.googleusercontent.com',
    iosBundleId: 'com.example.ultraLevelPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc4Dw9cmenZCDBiRJTlt0XYK_JrqmfVOQ',
    appId: '1:951810322846:ios:43cbb6b8f22e0a0492e68f',
    messagingSenderId: '951810322846',
    projectId: 'ultralevel-pro',
    storageBucket: 'ultralevel-pro.appspot.com',
    iosClientId: '951810322846-v8fph73o5e7v8ttu38e4ge5llblfmmuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ultraLevelPro.RunnerTests',
  );
}
